#Здесь могла бы быть ваша релклама!
#
#
#Данный конфиг позволит изменить координаты hub-острова, а также изменить кол-во, координаты и владельца примыкающих островов.
#Для того, чтобы правильно добавить больше островов в плагин, то нужно внизу конфига вставить следующий шаблон:
# land{}:
#    x: 0
#    y: 0
#    z: 0
#    owner: empty
#Заместо скобок вставьте индекс острова. К примеру, по умолчанию островов в конфиге три.
#Следовательно, добавленный остров будет называться land4
#
#И последнее: строка owner хранит ник игрока. Если в данную строку вставить заместо ника слово "empty", то плагин зачтёт данный остров
#доступный для заселения
#
#АВТОР ПЛАГИНА: DIVE
#
#Кол-во островов
lands_numbers: 3

#Координаты центрального острова
homexyz:
  x: 0
  y: 0
  z: 0
land1:
    x: 0
    y: 0
    z: 0
    owner: empty
land2:
    x: 0
    y: 0
    z: 0
    owner: empty
land3:
    x: 20
    y: 12
    z: 10
    owner: empty